name: Autodeployment
"on":
  push:
    branches:
      - "main"
      - "master"

concurrency:
  group: ${{ github.ref }}::autodeploy
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/pull-request.yml

  deploy-staging:
    needs: [check]
    uses: ./.github/workflows/deploy-staging.yml
