name: Autodeployment pipeline
"on":
  push:
    branches:
      - "main"

# Runs steps sequentially
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: "staging"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo 'Building...'

  deploy-staging:
    needs: ["build"]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "staging"

  deploy-prod:
    needs: ["build", "deploy-staging"]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "production"
