name: Deploy to production:latest
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    name: Deploy to production "latest" version
    steps:
      - id: get_latest_release
        name: Get the latest release name
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
      - name: Release information
        run: "echo \"Release\n- Version: ${{steps.get_latest_release.outputs.release}}\n- Id: ${{steps.get_latest_release.outputs.id}}'\n- Description: ${{steps.get_latest_release.outputs.description}}\""
      - uses: actions/checkout@v4
        with:
          ref: ${{steps.get_latest_release.outputs.release}}
      - name: List directory
        run: ls -la
      - name: Show version
        run: cat version.txt
