name: Deploy to production
"on":
  # Allows to call this job from another pipeline
  workflow_call:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    name: Deploy app
    steps:
      - name: Deploy
        run: echo 'deploying to production'
