name: Deploy to staging
"on":
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}::deploy-staging
  cancel-in-progress: true

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    name: Deploy app
    steps:
      - name: Deploy
        run: echo 'deploying to staging'
