name: Deploy
"on":
  # Allows to call this job from another pipeline
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: string

jobs:
  deploy-staging:
    if: inputs.environment == 'staging'
    uses: ./.github/workflows/deploy-staging.yml
  deploy-prod:
    if: inputs.environment == 'production'
    uses: ./.github/workflows/deploy-production.yml
