name: Deploy
"on":
  # Allows to call this job from another pipeline
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        options:
          - development
          - staging
          - production
        required: true
        type: choice

jobs:
  deploy:
    timeout-minutes: 15
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo
        run: echo 'deploying to ${{ inputs.environment }}'
