name: Deploy to staging
"on":
  # Allows to call this job from another pipeline
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-latest
    name: Deploy app
    steps:
      - name: Deploy
        run: echo 'deploying to staging'
