name: Deploy to production:latest
"on":
  # Allows to call this job from another pipeline
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    name: Deploy to production "latest" version
    steps:
      - uses: actions/checkout@v4
        with:
          ref: refs/tags/latest
      - name: Show version
        run: cat version.txt
