name: Pull request
"on":
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: "development"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo 'Building...'
  test:
    needs: [build]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: "development"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo 'Testing...'
  lint:
    needs: [build]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: "development"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo 'Linting...'
